---
#
#    Hinweis: Dieses Beispiel stammt von 
# https://galaxy.ansible.com/open-switch/opx-acl
#
- hosts: sw01
  vars:
    opx_acl:
    - operation: create
      acl_tbl_attr_data:
        name: l2_mac
        stage: 1
        priority: 102
        allowed-match-fields: [3, 6, 9, 21]
      acl_entries:
        - name: l2_mac_entry1
          priority: 512
          match,0,type: 3
          match,0,SRC_MAC_VALUE,addr: '50:10:6e:00:00:00'

  roles:
     - role: open-switch.opx-acl
       when: ansible_net_os_name is defined and
             ansible_net_os_name == "openswitch"
