---
- hosts: sw01
  vars:
    opx_mac:
    - operation: create
      mac_attr_data:
        mac-address: "00:3a:06:31:00:02"
        ifindex: 47
        vlan: "20"
      # mac_attr_type is required to specify
      mac_attr_type:
        base-mac/table/mac-address: "mac"
  roles:
     - role: open-switch.opx-mac
       when: ansible_net_os_name is defined and
             ansible_net_os_name == "openswitch"
