---
- hosts: sw01
  vars:
    opx_route_v4:
    - ip_and_mask: 198.51.100.0/24
      nexthop_ip:
        - 192.0.2.18
  roles:
     - role: open-switch.opx-system
       when: ansible_net_os_name is defined and 
             ansible_net_os_name == "openswitch"
